import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm p-8 border border-gray-100 space-y-6">
        <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
        
        <h2 className="text-xl font-semibold text-gray-800 mt-6">1. Acceptance of Terms</h2>
        <p className="text-gray-600 leading-relaxed">
          By accessing and using AI Damage Inspector Pro, you accept and agree to be bound by the terms and provision of this agreement.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">2. Nature of the Service (Disclaimer)</h2>
        <ul className="list-disc pl-5 space-y-2 text-gray-600">
          <li><strong>Estimates Only:</strong> The repair costs, severity ratings, and structural breakdown reports generated by this application are strictly AI-generated estimates based on localized market data. They are for informational and negotiation purposes only.</li>
          <li><strong>Not a Legal Quote:</strong> These estimates do not constitute a legally binding quote, an official insurance survey, or a guarantee of actual repair costs.</li>
          <li><strong>No Liability:</strong> AI Damage Inspector Pro and its developers are not liable for any financial discrepancies, disputes with mechanics, or damages resulting from reliance on the AI-generated reports. Always consult a certified professional mechanic or insurance surveyor for official quotes.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">3. Acceptable Use</h2>
        <p className="text-gray-600 leading-relaxed">
          Users agree not to use the service to upload illegal, explicit, or malicious content. Attempting to reverse-engineer, spam, or overwhelm our API endpoints will result in an immediate ban from the service.
        </p>

        <div className="pt-6">
          <Link href="/" className="text-blue-600 hover:text-blue-800 font-medium">← Back to Home</Link>
        </div>
      </div>
    </div>
  );
}